/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) google.targets; 1, 0, 0,118; 11-4-2012 21:21:14; /db/ztree/library/trees/xdctargets/xdctargets-f40x/src/ xlibrary

 */

