/* --COPYRIGHT--,EPL
 *  Copyright (c) 2008 Texas Instruments and others.
 *  All rights reserved. This program and the accompanying materials
 *  are made available under the terms of the Eclipse Public License v1.0
 *  which accompanies this distribution, and is available at
 *  http://www.eclipse.org/legal/epl-v10.html
 * 
 *  Contributors:
 *      Texas Instruments - initial implementation
 * 
 * --/COPYRIGHT--*/
/*!
 *  ======== ti.mcu.msp430 ========
 *  Grace support for the MSP430
 *
 *  This package provides the top-level runtime interface to the code
 *  generated by Grace.  At this time, the only function externally callable
 *  by applications is `Grace_init()`.  To
 *  use this function you must include the header file that declares its
 *  prototype.  For example,
 *  @p(code)
 *      #include <ti/mcu/msp430/Grace.h>
 *          :
 *      int main(void)
 *      {
 *          Grace_init();  // initialize device peripherals
 *             :           // do something interesting ...
 *          return (0);    // return status to C runtime
 *      }
 *  @p
 *  @a(Synopsys)
 *  @p(code)
 *      #include <ti/mcu/msp430/Grace.h>
 *
 *      void Grace_init(void)
 *  @p
 *  @a(Description)
 *  The function `Grace_init()` initializes the peripherals of your device
 *  according to the settings specified by your application's `.cfg` file.
 *  This file can be created "by hand" but is more typically created using
 *  the Grace graphical configuration tool.
 *
 *  `Grace_init()` assumes that, prior to execution, peripherals are in their
 *  power-on-reset state.  This allows it to to avoid spending unnecessary
 *  time and code space setting registers to default values already
 *  established by the hardware during reset.  However, this also means that
 *  `Grace_init()` can not be used to "soft reset" peripherals during
 *  runtime.
 *  @a(See Also)
 *  @p(blist)
 *     - {@link PLUGINS_ROOT/com.ti.sdo.grace.product.ui/welcome/Welcome_to_Grace.html Grace graphical configuration tool}
 *     - {@link ti.mcu.msp430.csl.CSL Grace file generation details}
 *  @p
 */
package ti.mcu.msp430 [1, 0, 0]
{
}
