/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets; 1, 0, 3,606; 11-4-2012 21:21:25; /db/ztree/library/trees/xdctargets/xdctargets-f40x/src/ xlibrary

 */

