/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) microsoft.targets; 1, 0, 2, 0,609; 11-4-2012 21:21:18; /db/ztree/library/trees/xdctargets/xdctargets-f40x/src/ xlibrary

 */

